/** @format */

// /src/pages/index.tsx
import "../app/globals.css";
import React from "react";
import Link from "next/link";
import Head from "next/head";
import { auth } from "../firebaseConfig";
import { signInWithEmailAndPassword } from "firebase/auth";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faForwardStep } from "@fortawesome/free-solid-svg-icons";
import dynamic from "next/dynamic";
const Joyride = dynamic(() => import("react-joyride"), { ssr: false });

// 將login函數改為接收email, password和狀態更新函數
async function login(
  email: string,
  password: string,
  setError: React.Dispatch<React.SetStateAction<boolean>>
) {
  try {
    await signInWithEmailAndPassword(auth, email, password);
    // 登入成功後的處理...
  } catch (error) {
    console.error(error);
    // 處理錯誤...
  }
};

export default function Home() {
  const [showSignup, setShowSignup] = useState(false); // 將狀態放在Home組件內部
  const [runJoyride, setRunJoyride] = useState(true);

  const joyrideSteps = [
    {
      target: ".welcome",
      content: "Hey there! Ready to rock the Taiwan Concert Map? 🎸  ",
      showProgress: true,
      styles: {
        options: {
          backgroundColor: "black", // 黑色背景
          borderRadius: "8px", // 圓角邊框
          width: "250px", // 調整寬度
          padding: "10px", // 內部填充
          borderWidth: "2px", // 邊框寬度
          borderColor: "white", // 白色邊框
          color: "white", // 文字顏色
        },
      },
    },
    // 更多步驟...
    {
      target: ".login-step",
      content: "Join the crew! Sign in to connect and share your vibe ✨",
      styles: {
        options: {
          backgroundColor: "black", // 黑色背景
          borderRadius: "8px", // 圓角邊框
          width: "250px", // 調整寬度
          padding: "10px", // 內部填充
          borderWidth: "2px", // 邊框寬度
          borderColor: "white", // 白色邊框
          color: "white", // 文字顏色
        },
      },
    },
    {
      target: ".map-step",
      content:
        "Discover where the magic happens! Pinpoint cool venues and events. 📍🎶",
      styles: {
        options: {
          backgroundColor: "black", // 黑色背景
          borderRadius: "8px", // 圓角邊框
          width: "250px", // 調整寬度
          padding: "10px", // 內部填充
          borderWidth: "2px", // 邊框寬度
          borderColor: "white", // 白色邊框
          color: "white", // 文字顏色
        },
      },
    },
  ];

  const handleJoyrideCallback = (data) => {
    const { status } = data;
    if (status === "finished" || status === "skipped") {
      setRunJoyride(false);
    }
  };

  // 使用login函數時需要傳入setError
  const handleLogin = (email: string, password: string) =>
    login(email, password, setShowSignup);

  return (
    <div className="flex flex-col h-screen justify-center items-center bg-primary-color text-secondary-color">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* 主容器 */}
      <div>
        {/* 主標題部分 */}
        <div className="text-white text-3xl p-8 text-center"></div>
        <div className="absolute top-[225px] right-[-210px] transform rotate-90 writing-mode-vertical-rl text-[100px] text-white leading-[0.8]">
          DRINK THE
          <br />
          POISON-
        </div>
        {/* 歡迎訊息部分 */}
        <div className="text-2xl p-8 text-center"></div>

        {/* 按鈕部分 */}
        <div className="flex justify-center p-8">
          <Link href="/concert">
            <button className="absolute bottom-[20px] left-[250px] text-white bg-green-500 px-4 py-2 border border-white rounded hover:bg-green-400">
              Enter
            </button>
          </Link>
        </div>
        <div className="absolute top-[280px] left-[-220px] transform rotate-90 writing-mode-vertical-rl text-[100px] text-tertiary-color leading-[0.8]">
          FROM THE
          <br />
          SAME VIBE·
          <br />▶ ıı|ıı|ıı|ıı 30 &quot;
        </div>
        <div className="absolute top-[50px] right-0">
          <img
            src="https://i.pinimg.com/564x/95/0b/d1/950bd14366d1919c0e4f873d9e8aa83f.jpg"
            alt="你的照片描述"
            width={600}
            height={600}
            className="transform rotate-90 opacity-75 filter"
          />
        </div>
      </Link>
      <div className="welcome"></div>
      <Joyride
        steps={joyrideSteps}
        run={runJoyride}
        callback={handleJoyrideCallback}
        locale={{
          last: "Finish", // 最後一步的按鈕文本
          next: "Next", // 下一步的按鈕文本
          skip: "Skip", // 跳過按鈕文本
          close: "Close", // 關閉按鈕文本
        }}
        showSkipButton={true}
        showProgress={true}
        continuous={true}
      />
    </div>
  );
}
